
name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hp-frontend:latest

    - name: Build and push gryffindor service
      uses: docker/build-push-action@v4
      with:
        context: ./services/gryffindor
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/gryffindor-service:latest

    - name: Build and push slytherin service
      uses: docker/build-push-action@v4
      with:
        context: ./services/slytherin
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/slytherin-service:latest

    - name: Build and push ravenclaw service
      uses: docker/build-push-action@v4
      with:
        context: ./services/ravenclaw
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ravenclaw-service:latest

    - name: Build and push hufflepuff service
      uses: docker/build-push-action@v4
      with:
        context: ./services/hufflepuff
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hufflepuff-service:latest
